spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: skill-drill
  messages:
    basename: messages/response-messages, messages/email-messages, messages/exception-messages
      
sender:
  email: ucfsgreenapex@gmail.com
  password: abcd1234@@
  

  
